### ISSUE TITLE
Order of record entries can cause crash in querying database

### ISSUE THREAD

**Issue by aljazkosmerlj** [qminer/qminer#606]
When querying the Base using a join over several different values of the same field the order of entries in the stores can cause an exception to be raised.  It appears some test, if the result ids are sorted, fails.

Example code:
```
var qm = require('qminer');

var base = new qm.Base({
    mode: 'createClean',
    schema: [
      { name: 'People',
        fields: [{ name: 'Name', type: 'string', primary: true, shortstring: true}],
        joins: [{ name: 'directed', 'type': 'index', 'store': 'Movies', 'inverse': 'director' }],
        keys: [{ field: 'Name', type: 'value'}] },
      { name: 'Movies',
        fields: [{ name: 'Title', type: 'string', primary: true }],
        joins: [{ name: 'director', 'type': 'field', 'store': 'People', 'inverse': 'directed' }],
        keys: [{ field: 'Title', type: 'value'}] }
    ]
});

// the search in line 32 works
// base.store('Movies').push({ Title: 'Broken Flowers', director: { Name: 'Jim Jarmusch' } });
// base.store('Movies').push({ Title: 'Coffee and Cigarettes', director: { Name: 'Jim Jarmusch' } });
// base.store('Movies').push({ Title: 'Dogville', director: { Name: 'Lars von Trier' } });

// the search in line 32 works
// base.store('Movies').push({ Title: 'Dogville', director: { Name: 'Lars von Trier' } });
// base.store('Movies').push({ Title: 'Broken Flowers', director: { Name: 'Jim Jarmusch' } });
// base.store('Movies').push({ Title: 'Coffee and Cigarettes', director: { Name: 'Jim Jarmusch' } });

// the search in line 32 crashes
base.store('Movies').push({ Title: 'Broken Flowers', director: { Name: 'Jim Jarmusch' } });
base.store('Movies').push({ Title: 'Dogville', director: { Name: 'Lars von Trier' } });
base.store('Movies').push({ Title: 'Coffee and Cigarettes', director: { Name: 'Jim Jarmusch' } });

let res = base.search({
  $join: {
    $name: "directed",
    $query: {
      $from: "People",
      Name: {$or: ["Jim Jarmusch", "Lars von Trier"]}
    }
  }
});

console.log('Record set:\n', res);
console.log('RESULTS:');
res.each(function (rec) {console.log(rec.Title, '-', rec.director.Name);});

base.close();
```

Exception raised:
```
TypeError: [addon] Exception: ../src/qminer/qminer_core.cpp line 6939: ResRecIdFqV.IsSorted()
    at Object.<anonymous> (/home/aljazk/ijs/TEMP/test_join.js:29:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by rupnikj** [comment]
Either we remove the Assert in https://github.com/qminer/qminer/blob/v9.1.2/src/qminer/qminer_core.cpp#L6939
or we add a sorting step.
@blazf suggestion?
